<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>


<h2>Objective</h2><ul><li> How to make a prediction using multiple samples.</li></ul> 



# Table of Contents
In this lab, we will  review how to make a prediction for Linear Regression with Multiple Output. 

<div class="alert alert-block alert-info" style="margin-top: 20px">

<li><a href="#ref1">Class Linear </a></li>

<br>
<p></p>
Estimated Time Needed: <strong>15 min</strong>
</div>

<hr>


<a id="ref1"></a>
<a name="ref1"><h2 align=center>Class Linear  </h2></a>


In [1]:
from torch import nn
import torch

Set the random seed:


In [2]:
torch.manual_seed(1)

Set the random seed:


In [3]:
class linear_regression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linear_regression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

create a linear regression  object, as our input and output will be two we set the parameters accordingly 


In [10]:
model=linear_regression(3,10)
model(torch.tensor([1.0,2.9,3.0]))

tensor([ 0.8370, -2.1800,  2.3270,  2.3345,  0.0128,  3.1301, -2.3058,  0.7963,
        -2.6424,  1.9651], grad_fn=<AddBackward0>)

we can use the diagram to represent the model or object 


<img src="https://ibm.box.com/shared/static/icmwnxru7nytlhnq5x486rffea9ncpk7.png" width="600," align="center">


we can see the parameters 


In [11]:
model.state_dict()

OrderedDict([('linear.weight',
              tensor([[ 0.5288, -0.1068,  0.3255],
                      [ 0.2500, -0.3732, -0.4910],
                      [ 0.5542,  0.0301,  0.3957],
                      [ 0.1196,  0.1857,  0.4313],
                      [ 0.5475, -0.3831,  0.0722],
                      [ 0.4309,  0.4183,  0.3587],
                      [-0.4178, -0.4158, -0.3492],
                      [ 0.0725,  0.5754, -0.3647],
                      [ 0.3077, -0.3196, -0.5428],
                      [-0.1227,  0.3327,  0.5360]])),
             ('linear.bias',
              tensor([-0.3586,  0.1253,  0.4982,  0.3826,  0.3598,  0.4103,  0.3652,  0.1491,
                      -0.3948, -0.4848]))])

In [5]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.5153],
         [-0.4414],
         [-0.1939],
         [ 0.4694],
         [-0.9414],
         [ 0.5997],
         [-0.2057],
         [ 0.5087],
         [ 0.1390],
         [-0.1224]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2774,  0.0493,  0.3652, -0.3897, -0.0729, -0.0900,  0.1449, -0.0040,
          0.8742,  0.3112], requires_grad=True)]

we can create a tensor with two rows representing one sample of data


In [15]:
x=torch.tensor([[1.0,2.0,3.0]])

we can make a prediction 


In [16]:
yhat=model(x)
yhat

tensor([[ 0.9331, -1.8441,  2.2999,  2.1674,  0.3576,  2.7537, -1.9317,  0.2784,
         -2.3548,  1.6658]], grad_fn=<AddmmBackward0>)

each row in the following tensor represents a different sample 


In [19]:
X=torch.tensor([[1.0,2.0,3.0],[1.0,-1.0,-3.0],[3.0,4.5,3.2]])

we can make a prediction using multiple samples 


In [20]:
Yhat=model(X)
Yhat

tensor([[ 0.9331, -1.8441,  2.2999,  2.1674,  0.3576,  2.7537, -1.9317,  0.2784,
         -2.3548,  1.6658],
        [-0.6995,  2.2215, -0.1650, -0.9772,  1.0738, -0.6531,  1.4106,  0.7403,
          1.8609, -2.5482],
        [ 1.7887, -2.3753,  3.5628,  2.9571,  0.5091,  4.7327, -3.8765,  1.7891,
         -2.6469,  2.3592]], grad_fn=<AddmmBackward0>)

the following figure represents the operation, where the red and blue  represents the different parameters, and the different shades of green represent  different samples.


 <img src="https://ibm.box.com/shared/static/768cul6pj8hc93uh9ujpajihnp8xdukx.png" width="600," align="center">



<a href="https://dataplatform.cloud.ibm.com/registration/stepone?utm_source=skills_network&utm_content=in_lab_content_link&utm_id=Lab-IBMDeveloperSkillsNetwork-DL0110EN-SkillsNetwork&context=cpdaas&apps=data_science_experience%2Cwatson_machine_learning"><img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DL0110EN-SkillsNetwork/Template/module%201/images/Watson_Studio.png"></a>


# About the Authors:  

 [Joseph Santarcangelo]( https://www.linkedin.com/in/joseph-s-50398b136/) has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.
 
Other contributors: [Michelle Carey](  https://www.linkedin.com/in/michelleccarey/) 


<!--
## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2020-09-23  | 2.0  | Shubham  |  Migrated Lab to Markdown and added to course repo in GitLab |

-->


## <h3 align="center"> &#169; IBM Corporation. All rights reserved. <h3/>
